# Logistic Regression with Python

### Import the library

In [613]:
import pandas as pd
import pylab as pl
import numpy as np
import scipy.optimize as opt
from sklearn import preprocessing
%matplotlib inline 
import matplotlib.pyplot as plt
print ("Done !")

Done !


### Load Data From CSV File  

In [685]:
train_df = pd.read_csv("el4233-2018-2019-02-klasifikasi-train.csv")
print(train_df.shape)
train_df.head()

(1000, 4)


No        X0        X1  Y
0   0  0.684314  1.102777  0
1   1  0.218752  0.122695  1
2   2  0.034522  0.329218  1
3   3 -0.323019  1.479858  0
4   4  2.303018 -0.369103  1

<h2 id="preprocessing">Data Preprocessing</h2>

Lets define X, and y for our dataset:

In [686]:
X = np.asarray(train_df[['X0', 'X1']])
X[0:5]

array([[ 0.68,  1.1 ],
       [ 0.22,  0.12],
       [ 0.03,  0.33],
       [-0.32,  1.48],
       [ 2.3 , -0.37]])

In [687]:
y = np.asarray(train_df['Y'])
y[0:5]

array([0, 1, 1, 0, 1])

Normalize the dataset

In [688]:
from sklearn import preprocessing
X = preprocessing.StandardScaler().fit(X).transform(X)

## Train/Test dataset

Okay, we split our dataset into train and test set:

In [751]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.2, random_state=4)
print ('Train set:', X_train.shape,  y_train.shape)
print ('Valid set:', X_test.shape,  y_test.shape)

Train set: (800, 2) (800,)
Valid set: (200, 2) (200,)


<h2 id="modeling">Modeling (Logistic Regression with Scikit-learn)</h2>

In [752]:
from sklearn.model_selection import cross_val_score

predicted = cross_val_score(LogisticRegression(C=0.1, solver='newton-cg').fit(X_train,y_train), X_train, y_train, cv=10)
predicted

array([0.84, 0.86, 0.88, 0.84, 0.81, 0.89, 0.9 , 0.88, 0.84, 0.86])

In [753]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
LR = LogisticRegression(C=0.1, solver='newton-cg').fit(X_train,y_train)
LR

LogisticRegression(C=0.1, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='newton-cg',
          tol=0.0001, verbose=0, warm_start=False)

yhat return the prediction of the X_test

In [754]:
yhat = LR.predict(X_test)
yhat

array([1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1,
       1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1,
       1, 1])

### Now, we can predict on our test set:

In [755]:
test_df = pd.read_csv("el4233-2018-2019-02-klasifikasi-test.csv")
print(test_df.shape)
test_df.head()

(1000, 3)


No        X0        X1
0  1000  1.030522  0.892364
1  1001  1.318739 -0.498590
2  1002  1.210100  0.498914
3  1003 -0.644977  1.346281
4  1004  0.042483  0.550473

In [756]:
X_testing = np.asarray(test_df[['X0', 'X1']])
X_testing

array([[ 1.03,  0.89],
       [ 1.32, -0.5 ],
       [ 1.21,  0.5 ],
       ...,
       [ 1.3 , -0.19],
       [ 0.23,  1.12],
       [ 0.03,  1.66]])

In [757]:
from sklearn import preprocessing
X_testing = preprocessing.StandardScaler().fit(X_testing).transform(X_testing)
X_testing[0:5]

array([[ 0.46,  0.61],
       [ 0.82, -1.54],
       [ 0.68,  0.  ],
       [-1.61,  1.31],
       [-0.76,  0.08]])

In [758]:
y_testing = LR.predict(X_testing)

In [759]:
test_df['prediksi'] = y_testing
test_df = test_df.set_index('No')
test_df.head()

X0        X1  prediksi
No                                
1000  1.030522  0.892364         0
1001  1.318739 -0.498590         1
1002  1.210100  0.498914         1
1003 -0.644977  1.346281         0
1004  0.042483  0.550473         1

In [760]:
test_df.to_csv('el4233-2018-2019-02-klasifikasi-submit-Logistic_Regression.csv')

references :
[cognitiveclass.ai](https://cognitiveclass.ai)